### ISSUE TITLE
Indented single quoted HereDoc returns true for interpolates

### ISSUE THREAD

**Issue by oalders** [trwyant/perl-PPIx-QuoteLike#1]
First off, thanks so much for your work. I tried to implement it in some $work code earlier today and I ran into this:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use PPI::Document   ();
use PPIx::QuoteLike ();
use Test::More;

my $heredoc = q{
use strict;

my $sql = <<~'SQL';
SELECT %{foo}
SQL
};

my $doc      = PPI::Document->new( \$heredoc );
my $elements = $doc->find( sub { $_[1]->isa('PPI::Token::HereDoc') } );

my $str = PPIx::QuoteLike->new( $elements->[0] );
ok( !$str->interpolates, 'does not interpolate' );
```

That test fails for me. I haven't looked to closely at the code, but my guess is there needs to be an allowance for indented heredocs.

**Comment by trwyant** [comment]
Thank you very much for your report. Your analysis appears to be correct, but unfortunately the fix is not as simple as recognizing an optional '~' before the optional quotes. And because I dropped the ball when indented here docs were added I will have to go back and dig out when that was.

All the same, it's not like I have to completely redo the internals. Please rattle my cage if you have not heard anything from me by February 3 2021.

Thanks again for the opportunity to make this module better, and (frankly) for letting me know someone is actually using it.

**Comment by oalders** [comment]
Thanks for your very quick response. :) I had a quick check and it looks like https://metacpan.org/release/App-p5find and https://metacpan.org/release/Perl-Critic depend on this module, so it's getting used!

```
$ git grep PPIx::QuoteLike
cpanfile:32:requires 'PPIx::QuoteLike'            => 0;
inc/Perl/Critic/BuildUtilities.pm:53:        'PPIx::QuoteLike'               => 0,
lib/Perl/Critic/Policy/Variables/ProhibitUnusedVariables.pm:11:use PPIx::QuoteLike;
lib/Perl/Critic/Policy/Variables/ProhibitUnusedVariables.pm:92:            my $str = PPIx::QuoteLike->new( $double_quotish
```

**Comment by trwyant** [comment]
I have looked into this a bit more, and it looks like the PPI::Token::HereDoc object does not preserve the indentation, though it does know the object was indented. This means that, pending changes in PPI, I will not be able to recover the original source. PPI can't either, as demonstrated by calling PPI::Document->serialize() on a document containing an indented here doc.

**Comment by oalders** [comment]
Are you referring to https://github.com/adamkennedy/PPI/issues/251?

**Comment by oalders** [comment]
Maybe I'm misunderstanding the problem, but in the example above, `$elements->[0]` stringifies to `<<~'SQL'`. Would it be enough to have code examine that content to determine if the heredoc is double quoted?

**Comment by trwyant** [comment]
I have not looked into the PPI side beyond determining that indentation is lost, though the fact that it is indented is not. But it looks to me like you are right: it is  adamkennedy/PPI#251 or something very much like it.

This does not prevent me fixing your issue, it just means I can't recover the original source of a PPI::Token::HereDoc.

**Comment by trwyant** [comment]
Just pushed to GitHub. The push includes the commit that (hopefully) resolves the indented-here-document problem, plus another that recognizes \EOD. Let me know what you think. If you'd rather work with a development distribution (either from me directly or from CPAN) just let me know.

**Comment by oalders** [comment]
This is great! Thanks so much. That test snippet passes with those changes. What I'd like to do is replace this logic with yours: https://metacpan.org/source/AUBERTG/Perl-Critic-Policy-ValuesAndExpressions-PreventSQLInjection-v1.4.0/lib/Perl/Critic/Policy/ValuesAndExpressions/PreventSQLInjection.pm#L686-693

I can do that once this is on CPAN.

**Comment by trwyant** [comment]
Version 0.014_01 just went to PAUSE.

The thing is, you are working from a PPI::Token::HereDoc, right? PPIx::QuoteLike will handle one of those, but it only uses the public interface to do so. So if my interpolates() really gives you what you want, you may be able to do it yourself without adding a dependency. Looking at my code, you may be able to infer interpolation from the PPI::Token::HereDoc public interface by replacing your encapsulation violation with something like

`return if $token->content() =~ m/\A<<\s*~\s*[\\']/`

**Comment by oalders** [comment]
Yes, that's true. Thanks for that. I'm not *too* worried about the additional dependency as it's already in `Perl::Critic` and I'm just working on a policy for it.

**Comment by trwyant** [comment]
Production release of PPIx-QuoteLike went to PAUSE yesterday (February 5).

**Comment by oalders** [comment]
Thanks @trwyant! I also came across your PPI PR for indented heredocs. I've got some $work code that uses indented heredocs extensively, so I hope to test that PR out on Monday.
